const images = [
    require('./Sheeran/1e839297489f85e77ebeff79f208f00c.jpg'),
    require('./Sheeran/51bed08814f4e33d2fef4638455246ae.jpg'),
    require('./Sheeran/933b961e2d4a807534fcedfbc10f610d.png'),
    require('./Sheeran/IMG_1583.png'),
    require('./Sheeran/edsheeranlookalike2.jpg'),
    require('./Sheeran/maxresdefault.jpg'),
    require('./Sheeran/trulySheeran.jpg'),
    require('./Sheeran/trulySheeran1.jpg'),
    require('./Sheeran/trulySheeran2.png'),
    require('./Sheeran/trulySheeran3.png'),
    require('./Sheeran/trulySheeran4.png'),
    require('./Sheeran/trulySheeran5.jpg'),
    require('./Sheeran/trulySheeran6.png'),
    require('./Sheeran/trulySheeran7.png'),
    require('./Sheeran/trulySheeran8.png'),
    require('./Sheeran/trulySheeran9.jpg'),
    require('./Sheeran/trulySheeran10.jpg'),
    require('./Sheeran/trulySheeran11.png'),
    require('./Sheeran/trulySheeran12.jpg'),
    require('./Sheeran/trulySheeran13.jpg'),
    require('./Sheeran/new1.png'),
    require('./Sheeran/new2.png'),
    require('./Sheeran/new3.png'),
    require('./Sheeran/new4.png'),
    require('./Sheeran/new5.png'),
    require('./Sheeran/new6.png'),
    require('./Sheeran/new7.png'),
    require('./Sheeran/new8.png'),
    require('./Sheeran/new9.png'),
    require('./Sheeran/new10.png'),
    require('./Sheeran/new11.jpeg'),
    require('./Sheeran/new12.png'),
    require('./Sheeran/new13.png'),
]

export default images